In [56]:
import pandas as pd
import requests
import json

In [57]:
district_data_url = 'https://data.covid19india.org/v4/min/data.min.json'
district_data = requests.get(district_data_url)
data = district_data.json()

In [58]:
district = []

# Loop over all states
for state_code, state_data in data.items():
    # Loop over all districts within each state
    for district_code, district_data in state_data.get('districts', {}).items():
        # Extract relevant data categories
        confirmed_total = district_data.get('total', {}).get('confirmed', 0)
        recovered_total = district_data.get('total', {}).get('recovered', 0)
        deceased_total = district_data.get('total', {}).get('deceased', 0)
        tested_total = district_data.get('total', {}).get('tested', 0)
        vaccinated1_total = district_data.get('total', {}).get('vaccinated1', 0)
        vaccinated2_total = district_data.get('total', {}).get('vaccinated2', 0)
         #delta
        confirmed_delta = district_data.get('delta', {}).get('confirmed', 0)
        recovered_delta = district_data.get('delta', {}).get('recovered', 0)
        deceased_delta = district_data.get('delta', {}).get('deceased', 0)
        vaccinated1_delta = district_data.get('delta', {}).get('vaccinated1', 0)
        vaccinated2_delta = district_data.get('delta', {}).get('vaccinated2', 0)
         #delta7
        confirmed_delta7 = district_data.get('delta7', {}).get('confirmed', 0)
        recovered_delta7 = district_data.get('delta7', {}).get('recovered', 0)
        deceased_delta7 = district_data.get('delta7', {}).get('deceased', 0)
        vaccinated1_delta7 = district_data.get('delta7', {}).get('vaccinated1', 0)
        vaccinated2_delta7 = district_data.get('delta7', {}).get('vaccinated2', 0)
        #meta
        population_meta = district_data.get('meta', {}).get('population', 0)
        tested_meta = district_data.get('meta', {}).get('tested', {}).get('date', 0)
        last_updated_meta = district_data.get('meta', {}).get('last_updated', 0)
        notes_meta = district_data.get('meta', {}).get('notes', 0)
        date_meta = district_data.get('meta', {}).get('date', 0)
        # Adding data to list of dictionaries
        district_dict = {
            'state_code': state_code,
            'district_code': district_code,
            #total
            'confirmed_total': confirmed_total,
            'recovered_total': recovered_total,
            'deceased_total': deceased_total,
            'tested_total': tested_total,
            'vaccinated1_total': vaccinated1_total,
            'vaccinated2_total': vaccinated2_total,
            #delta
            'confirmed_delta': confirmed_delta,
            'recovered_delta': recovered_delta,
            'deceased_delta': deceased_delta,
            'vaccinated1_delta': vaccinated1_delta,
            'vaccinated2_delta': vaccinated2_delta,
            #delta7
            'confirmed_delta7': confirmed_delta7,
            'recovered_delta7': recovered_delta7,
            'deceased_delta7': deceased_delta7,
            'vaccinated1_delta7': vaccinated1_delta7,
            'vaccinated2_delta7': vaccinated2_delta7,
            #meta
            'population_meta': population_meta,
            'tested_meta' : tested_meta,
            'last_updated_meta' : last_updated_meta,
            'notes_meta' : notes_meta,
            'date_meta' : date_meta

        }
        district.append(district_dict)

# Convert list of dictionaries to DataFrame
district = pd.DataFrame(district)

district.to_csv("district_covid_data.csv", index=False)

In [59]:
district.head()

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,...,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta,last_updated_meta,notes_meta,date_meta
0,AN,Nicobars,0,0,0,0,25394,20313,0,0,...,0,0,0,62,811,36842,0,0,0,0
1,AN,North and Middle Andaman,0,0,0,0,78945,59522,0,0,...,0,0,0,90,1839,105597,0,0,0,0
2,AN,South Andaman,0,0,0,0,189662,120322,0,0,...,0,0,0,732,8012,238142,0,0,0,0
3,AN,Unknown,7651,7518,129,0,0,0,0,0,...,3,5,0,0,0,0,0,0,0,0
4,AP,Anantapur,157843,156699,1093,787085,2690082,1611476,4,5,...,38,58,0,92803,140903,4083315,2020-11-26,0,0,0

In [60]:
district.shape

(748, 23)

In [61]:
district.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state_code          748 non-null    object
 1   district_code       748 non-null    object
 2   confirmed_total     748 non-null    int64
 3   recovered_total     748 non-null    int64
 4   deceased_total      748 non-null    int64
 5   tested_total        748 non-null    int64
 6   vaccinated1_total   748 non-null    int64
 7   vaccinated2_total   748 non-null    int64
 8   confirmed_delta     748 non-null    int64
 9   recovered_delta     748 non-null    int64
 10  deceased_delta      748 non-null    int64
 11  vaccinated1_delta   748 non-null    int64
 12  vaccinated2_delta   748 non-null    int64
 13  confirmed_delta7    748 non-null    int64
 14  recovered_delta7    748 non-null    int64
 15  deceased_delta7     748 non-null    int64
 16  vaccinated1_delta7  748 non-null    int64
 17  vaccinated2_delta7  748 non-null    int64
 18  population_meta     748 non-null    int64
 19  tested_meta         748 non-null    object
 20  last_updated_meta   748 non-null    int64
 21  notes_meta          748 non-null    object
 22  date_meta           748 non-null    int64
dtypes: int64(19), object(4)
memory usage: 134.5+ KB

In [62]:
# for checking unique values
for i in district:
  print(i)
  print(district[i].unique())
  print()

state_code
['AN' 'AP' 'AR' 'AS' 'BR' 'CH' 'CT' 'DL' 'DN' 'GA' 'GJ' 'HP' 'HR' 'JH'
 'JK' 'KA' 'KL' 'LA' 'LD' 'MH' 'ML' 'MN' 'MP' 'MZ' 'NL' 'OR' 'PB' 'PY'
 'RJ' 'SK' 'TG' 'TN' 'TR' 'UP' 'UT' 'WB']

district_code
['Nicobars' 'North and Middle Andaman' 'South Andaman' 'Unknown'
 'Anantapur' 'Chittoor' 'East Godavari' 'Foreign Evacuees' 'Guntur'
 'Krishna' 'Kurnool' 'Other State' 'Prakasam' 'S.P.S. Nellore'
 'Srikakulam' 'Visakhapatnam' 'Vizianagaram' 'West Godavari'
 'Y.S.R. Kadapa' 'Anjaw' 'Capital Complex' 'Changlang' 'East Kameng'
 'East Siang' 'Kamle' 'Kra Daadi' 'Kurung Kumey' 'Lepa Rada' 'Lohit'
 'Longding' 'Lower Dibang Valley' 'Lower Siang' 'Lower Subansiri' 'Namsai'
 'Pakke Kessang' 'Papum Pare' 'Shi Yomi' 'Siang' 'Tawang' 'Tirap'
 'Upper Dibang Valley' 'Upper Siang' 'Upper Subansiri' 'West Kameng'
 'West Siang' 'Baksa' 'Barpeta' 'Biswanath' 'Bongaigaon' 'Cachar'
 'Charaideo' 'Chirang' 'Darrang' 'Dhemaji' 'Dhubri' 'Dibrugarh'
 'Dima Hasao' 'Goalpara' 'Golaghat' 'Hailakandi' 'Hojai' 'Jorhat' 'Kamrup'
 'Kamrup Metropolitan' 'Karbi Anglong' 'Karimganj' 'Kokrajhar' 'Lakhimpur'
 'Majuli' 'Morigaon' 'Nagaon' 'Nalbari' 'Sivasagar' 'Sonitpur'
 'South Salmara Mankachar' 'Tinsukia' 'Udalguri' 'West Karbi Anglong'
 'Araria' 'Arwal' 'Aurangabad' 'Banka' 'Begusarai' 'Bhagalpur' 'Bhojpur'
 'Buxar' 'Darbhanga' 'East Champaran' 'Gaya' 'Gopalganj' 'Jamui'
 'Jehanabad' 'Kaimur' 'Katihar' 'Khagaria' 'Kishanganj' 'Lakhisarai'
 'Madhepura' 'Madhubani' 'Munger' 'Muzaffarpur' 'Nalanda' 'Nawada' 'Patna'
 'Purnia' 'Rohtas' 'Saharsa' 'Samastipur' 'Saran' 'Sheikhpura' 'Sheohar'
 'Sitamarhi' 'Siwan' 'Supaul' 'Vaishali' 'West Champaran' 'Chandigarh'
 'Balod' 'Baloda Bazar' 'Balrampur' 'Bametara' 'Bastar' 'Bijapur'
 'Bilaspur' 'Dakshin Bastar Dantewada' 'Dhamtari' 'Durg' 'Gariaband'
 'Gaurela Pendra Marwahi' 'Janjgir Champa' 'Jashpur' 'Kabeerdham'
 'Kondagaon' 'Korba' 'Koriya' 'Mahasamund' 'Mungeli' 'Narayanpur'
 'Raigarh' 'Raipur' 'Rajnandgaon' 'Sukma' 'Surajpur' 'Surguja'
 'Uttar Bastar Kanker' 'Delhi' 'Dadra and Nagar Haveli' 'Daman' 'Diu'
 'North Goa' 'South Goa' 'Ahmedabad' 'Amreli' 'Anand' 'Aravalli'
 'Banaskantha' 'Bharuch' 'Bhavnagar' 'Botad' 'Chhota Udaipur' 'Dahod'
 'Dang' 'Devbhumi Dwarka' 'Gandhinagar' 'Gir Somnath' 'Jamnagar'
 'Junagadh' 'Kheda' 'Kutch' 'Mahisagar' 'Mehsana' 'Morbi' 'Narmada'
 'Navsari' 'Panchmahal' 'Patan' 'Porbandar' 'Rajkot' 'Sabarkantha' 'Surat'
 'Surendranagar' 'Tapi' 'Vadodara' 'Valsad' 'Chamba' 'Hamirpur' 'Kangra'
 'Kinnaur' 'Kullu' 'Lahaul and Spiti' 'Mandi' 'Shimla' 'Sirmaur' 'Solan'
 'Una' 'Ambala' 'Bhiwani' 'Charkhi Dadri' 'Faridabad' 'Fatehabad'
 'Gurugram' 'Hisar' 'Jhajjar' 'Jind' 'Kaithal' 'Karnal' 'Kurukshetra'
 'Mahendragarh' 'Nuh' 'Palwal' 'Panchkula' 'Panipat' 'Rewari' 'Rohtak'
 'Sirsa' 'Sonipat' 'Yamunanagar' 'Bokaro' 'Chatra' 'Deoghar' 'Dhanbad'
 'Dumka' 'East Singhbhum' 'Garhwa' 'Giridih' 'Godda' 'Gumla' 'Hazaribagh'
 'Jamtara' 'Khunti' 'Koderma' 'Latehar' 'Lohardaga' 'Pakur' 'Palamu'
 'Ramgarh' 'Ranchi' 'Sahibganj' 'Saraikela-Kharsawan' 'Simdega'
 'West Singhbhum' 'Anantnag' 'Bandipora' 'Baramulla' 'Budgam' 'Doda'
 'Ganderbal' 'Jammu' 'Kathua' 'Kishtwar' 'Kulgam' 'Kupwara' 'Pulwama'
 'Punch' 'Rajouri' 'Ramban' 'Reasi' 'Samba' 'Shopiyan' 'Srinagar'
 'Udhampur' 'Bagalkote' 'Ballari' 'Belagavi' 'Bengaluru Rural'
 'Bengaluru Urban' 'Bidar' 'Chamarajanagara' 'Chikkaballapura'
 'Chikkamagaluru' 'Chitradurga' 'Dakshina Kannada' 'Davanagere' 'Dharwad'
 'Gadag' 'Hassan' 'Haveri' 'Kalaburagi' 'Kodagu' 'Kolar' 'Koppal' 'Mandya'
 'Mysuru' 'Raichur' 'Ramanagara' 'Shivamogga' 'Tumakuru' 'Udupi'
 'Uttara Kannada' 'Vijayapura' 'Yadgir' 'Alappuzha' 'Ernakulam' 'Idukki'
 'Kannur' 'Kasaragod' 'Kollam' 'Kottayam' 'Kozhikode' 'Malappuram'
 'Palakkad' 'Pathanamthitta' 'Thiruvananthapuram' 'Thrissur' 'Wayanad'
 'Kargil' 'Leh' 'Lakshadweep' 'Ahmednagar' 'Akola' 'Amravati' 'Beed'
 'Bhandara' 'Buldhana' 'Chandrapur' 'Dhule' 'Gadchiroli' 'Gondia'
 'Hingoli' 'Jalgaon' 'Jalna' 'Kolhapur' 'Latur' 'Mumbai' 'Nagpur' 'Nanded'
 'Nandurbar' 'Nashik' 'Osmanabad' 'Palghar' 'Parbhani' 'Pune' 'Raigad'
 'Ratnagiri' 'Sangli' 'Satara' 'Sindhudurg' 'Solapur' 'Thane' 'Wardha'
 'Washim' 'Yavatmal' 'East Garo Hills' 'East Jaintia Hills'
 'East Khasi Hills' 'North Garo Hills' 'Ribhoi' 'South Garo Hills'
 'South West Garo Hills' 'South West Khasi Hills' 'West Garo Hills'
 'West Jaintia Hills' 'West Khasi Hills' 'Bishnupur' 'Chandel'
 'Churachandpur' 'Imphal East' 'Imphal West' 'Jiribam' 'Kakching'
 'Kamjong' 'Kangpokpi' 'Noney' 'Pherzawl' 'Senapati' 'Tamenglong'
 'Tengnoupal' 'Thoubal' 'Ukhrul' 'Agar Malwa' 'Alirajpur' 'Anuppur'
 'Ashoknagar' 'Balaghat' 'Barwani' 'Betul' 'Bhind' 'Bhopal' 'Burhanpur'
 'Chhatarpur' 'Chhindwara' 'Damoh' 'Datia' 'Dewas' 'Dhar' 'Dindori' 'Guna'
 'Gwalior' 'Harda' 'Hoshangabad' 'Indore' 'Jabalpur' 'Jhabua' 'Katni'
 'Khandwa' 'Khargone' 'Mandla' 'Mandsaur' 'Morena' 'Narsinghpur' 'Neemuch'
 'Niwari' 'Panna' 'Raisen' 'Rajgarh' 'Ratlam' 'Rewa' 'Sagar' 'Satna'
 'Sehore' 'Seoni' 'Shahdol' 'Shajapur' 'Sheopur' 'Shivpuri' 'Sidhi'
 'Singrauli' 'Tikamgarh' 'Ujjain' 'Umaria' 'Vidisha' 'Aizawl' 'Champhai'
 'Hnahthial' 'Khawzawl' 'Kolasib' 'Lawngtlai' 'Lunglei' 'Mamit' 'Saiha'
 'Saitual' 'Serchhip' 'Dimapur' 'Kiphire' 'Kohima' 'Longleng' 'Mokokchung'
 'Mon' 'Peren' 'Phek' 'Tuensang' 'Wokha' 'Zunheboto' 'Angul' 'Balangir'
 'Balasore' 'Bargarh' 'Bhadrak' 'Boudh' 'Cuttack' 'Deogarh' 'Dhenkanal'
 'Gajapati' 'Ganjam' 'Jagatsinghpur' 'Jajpur' 'Jharsuguda' 'Kalahandi'
 'Kandhamal' 'Kendrapara' 'Kendujhar' 'Khordha' 'Koraput' 'Malkangiri'
 'Mayurbhanj' 'Nabarangapur' 'Nayagarh' 'Nuapada' 'Puri' 'Rayagada'
 'Sambalpur' 'State Pool' 'Subarnapur' 'Sundargarh' 'Amritsar' 'Barnala'
 'Bathinda' 'Faridkot' 'Fatehgarh Sahib' 'Fazilka' 'Ferozepur' 'Gurdaspur'
 'Hoshiarpur' 'Jalandhar' 'Kapurthala' 'Ludhiana' 'Mansa' 'Moga'
 'Pathankot' 'Patiala' 'Rupnagar' 'S.A.S. Nagar' 'Sangrur'
 'Shahid Bhagat Singh Nagar' 'Sri Muktsar Sahib' 'Tarn Taran' 'Karaikal'
 'Mahe' 'Puducherry' 'Yanam' 'Ajmer' 'Alwar' 'BSF Camp' 'Banswara' 'Baran'
 'Barmer' 'Bharatpur' 'Bhilwara' 'Bikaner' 'Bundi' 'Chittorgarh' 'Churu'
 'Dausa' 'Dholpur' 'Dungarpur' 'Evacuees' 'Ganganagar' 'Hanumangarh'
 'Italians' 'Jaipur' 'Jaisalmer' 'Jalore' 'Jhalawar' 'Jhunjhunu' 'Jodhpur'
 'Karauli' 'Kota' 'Nagaur' 'Pali' 'Pratapgarh' 'Rajsamand'
 'Sawai Madhopur' 'Sikar' 'Sirohi' 'Tonk' 'Udaipur' 'East Sikkim'
 'North Sikkim' 'South Sikkim' 'West Sikkim' 'Adilabad'
 'Bhadradri Kothagudem' 'Hyderabad' 'Jagtial' 'Jangaon'
 'Jayashankar Bhupalapally' 'Jogulamba Gadwal' 'Kamareddy' 'Karimnagar'
 'Khammam' 'Komaram Bheem' 'Mahabubabad' 'Mahabubnagar' 'Mancherial'
 'Medak' 'Medchal Malkajgiri' 'Mulugu' 'Nagarkurnool' 'Nalgonda'
 'Narayanpet' 'Nirmal' 'Nizamabad' 'Peddapalli' 'Rajanna Sircilla'
 'Ranga Reddy' 'Sangareddy' 'Siddipet' 'Suryapet' 'Vikarabad' 'Wanaparthy'
 'Warangal Rural' 'Warangal Urban' 'Yadadri Bhuvanagiri'
 'Airport Quarantine' 'Ariyalur' 'Chengalpattu' 'Chennai' 'Coimbatore'
 'Cuddalore' 'Dharmapuri' 'Dindigul' 'Erode' 'Kallakurichi' 'Kancheepuram'
 'Kanyakumari' 'Karur' 'Krishnagiri' 'Madurai' 'Mayiladuthurai'
 'Nagapattinam' 'Namakkal' 'Nilgiris' 'Perambalur' 'Pudukkottai'
 'Railway Quarantine' 'Ramanathapuram' 'Ranipet' 'Salem' 'Sivaganga'
 'Tenkasi' 'Thanjavur' 'Theni' 'Thiruvallur' 'Thiruvarur' 'Thoothukkudi'
 'Tiruchirappalli' 'Tirunelveli' 'Tirupathur' 'Tiruppur' 'Tiruvannamalai'
 'Vellore' 'Viluppuram' 'Virudhunagar' 'Dhalai' 'Gomati' 'Khowai'
 'North Tripura' 'Sipahijala' 'South Tripura' 'Unokoti' 'West Tripura'
 'Agra' 'Aligarh' 'Ambedkar Nagar' 'Amethi' 'Amroha' 'Auraiya' 'Ayodhya'
 'Azamgarh' 'Baghpat' 'Bahraich' 'Ballia' 'Banda' 'Barabanki' 'Bareilly'
 'Basti' 'Bhadohi' 'Bijnor' 'Budaun' 'Bulandshahr' 'Chandauli'
 'Chitrakoot' 'Deoria' 'Etah' 'Etawah' 'Farrukhabad' 'Fatehpur'
 'Firozabad' 'Gautam Buddha Nagar' 'Ghaziabad' 'Ghazipur' 'Gonda'
 'Gorakhpur' 'Hapur' 'Hardoi' 'Hathras' 'Jalaun' 'Jaunpur' 'Jhansi'
 'Kannauj' 'Kanpur Dehat' 'Kanpur Nagar' 'Kasganj' 'Kaushambi'
 'Kushinagar' 'Lakhimpur Kheri' 'Lalitpur' 'Lucknow' 'Maharajganj'
 'Mahoba' 'Mainpuri' 'Mathura' 'Mau' 'Meerut' 'Mirzapur' 'Moradabad'
 'Muzaffarnagar' 'Pilibhit' 'Prayagraj' 'Rae Bareli' 'Rampur' 'Saharanpur'
 'Sambhal' 'Sant Kabir Nagar' 'Shahjahanpur' 'Shamli' 'Shrawasti'
 'Siddharthnagar' 'Sitapur' 'Sonbhadra' 'Sultanpur' 'Unnao' 'Varanasi'
 'Almora' 'Bageshwar' 'Chamoli' 'Champawat' 'Dehradun' 'Haridwar'
 'Nainital' 'Pauri Garhwal' 'Pithoragarh' 'Rudraprayag' 'Tehri Garhwal'
 'Udham Singh Nagar' 'Uttarkashi' 'Alipurduar' 'Bankura' 'Birbhum'
 'Cooch Behar' 'Dakshin Dinajpur' 'Darjeeling' 'Hooghly' 'Howrah'
 'Jalpaiguri' 'Jhargram' 'Kalimpong' 'Kolkata' 'Malda' 'Murshidabad'
 'Nadia' 'North 24 Parganas' 'Paschim Bardhaman' 'Paschim Medinipur'
 'Purba Bardhaman' 'Purba Medinipur' 'Purulia' 'South 24 Parganas'
 'Uttar Dinajpur']

confirmed_total
[      0    7651  157843  246935  293836     434  178068  119348  124142
    2461  138482  146388  123109  157737   82967  179077  115623    1068
    3807    1094    3206     512     270     511     874    2885     752
    2426     738    3036    2124     453   18316     262     411    2577
    1109     337    1016    1958    3545    1868  610645   14978    7381
   20011    7379   27212   25840   10210    9248   10937   19017   33952
   16685    9418   10783    4984   18145   10064   10128    7776   12547
   18365   15111   31398   23432   10353  147007   24427   13980   17616
   20020   23278    7693    4404    9185   15195   17222   19827   20890
   65351   27278   43085   20302   19963   21066    8324   65681   10840
   27239   96880   19701   12011   57636   27093   22771   13139   54847
   26980   31365   23921    4019     805   62590  158035   56077    8066
   29029   33673   23636 1439870    5920    3543    1218  178108  238334
   10810    9637    5186   13631   11426   21447    2218    3395    9955
     866    4175   20754    8570   34978   20505   10439   12631    8194
   24419    6502    5955    7215     162   11770   11624    3486   57976
    9317  143874    8121    4441   78159    6405   14374   13687   17379
   50818    3507    9692    2953   31606   27549   15456   22817   14268
   30150   22409    5078   99902   17875  181428   53995   18849   21209
   11244   40037   22147   21689    5014   11025   30770   31150   20327
   25903   29282   47138   24631   19461    6033   10835   16589    4636
   51974    6895    8964    5840    9900   19593    5599    7820   12872
    7871    6709    2552   12294   13923   86116    4834    7207    7193
   13054   16603    9814   24613   23844    7869   10436   53324    9327
    4819   11489   14463   15512    6482   11272    6043    6626    7152
    5607   75539   11415   35178   97763   79900   62005 1251872   24340
   33001   43951   51126   36666  115478   50989   60970   26066  111785
   21947   61926   37095   46916   35198   73753  179167      36   39973
   24204   69444  120836   76718   56218   36267   27545  316160  602800
  147118  275264  138815  390872  322484  527346  567584  373839  193406
  463977  523260  125732    3619   17343   10365  339457   58764   96231
  155331  103749   60080   85520   88968   46172   30440   40519   18475
  139934   60615  206671   92133  756749  493607   90409   40006  410681
   67828     144  138013   52362 1154776  195958   78950  209771  250414
   52783  210466  610128   57344   41663   75967    1867    2430   41025
    1685    9697    1216    1872    2548    9027    6803    5457  123731
    3303    3505    9238    3670    9100    8366   12905    2995  123552
    2568    7609    6734    8120    6959    7723   12572    4623    5132
   53106    5055   10688  153230   50779    7691    9366    4044   13970
    5188    8637    8236   11209    7926    3715    7331       1    8729
   17860   16433   16622   11965   10136    6775   10085    6349    4000
   12398    9219    8801    6863   18903    6294    1416   11922   75111
    1020     733    7721    6740    9842    4854    5469     471    4210
   14684     258    9461     307    2333    1159     920     601     402
     623   43920   23397   40787   31126   26480   12634   94631    6553
   19871    9657   33849   27920   43735   23863   24314   11537   24860
   20980  175335   19137   11667   40844   23549   23505   22924   45431
   20224   31651   32048   13187   61841   47379    5950   41728   13927
    8876   20271   14347   22381   30822   63396   17852   87608   15606
    8675   18814   48927   12963   68821   15762   11469   18784    8043
   16488    5867   98885    6773   37769   59694      85   10005   11996
   15563   19601   29781   40339    7967   19809   16720   13351   11010
   18407      61   19354   16053       2  187804   13639   10067   13612
   14811  112412    7156   57053   17737     189   27324    7143   17044
   10618   30618   13732    9498   56405   31979  671463    2113   16854
  171777  554672  246780   64085   28425   33099  104303   31364   74970
   62362   24091   43570   75215   23280   21074   52245   33566   12067
   30183     428   20564   43436   99893   20195   27357   75352   43571
  119370   41461   56304   77534   49374   29301   95405   54968   49864
   45857   46294    7037    8134    4559    7250    6360   10168    8609
   32351   25765   21280    5040    9972   16616   10090   16919   17906
    9132   11549   21610    7494   10992   19850   44028   11717    7720
   14794   14941   20215   16208    7110   20223    9968   13933   10348
    6814    8720   63353   55673   21641   12282   59439    5232   12638
   13755    2920   11687   22584   36556    9231    6197   82933    4250
    4424   15617   24410   12742  238839   12440    4268   10028   20297
    8333   69480   11088   39102   31009   11032   16038   78699   17104
   11826   32730    9438    8159   20361   12976    4388    9373   16807
   14915   15011   85501   12190    5764   12242    7603  112363   51498
   39232   17686   10260    8800   15835   37875   12548   15589   36313
   41197   29275   17889   57143   86300   98757   41982   12135    7036
  322541   33406   33993   73333  329257      66   57778   53581   42005
   63098   19419  100957   19858]

recovered_total
[      0    7518  156699  244144  291610     434  176629  117130  123264
    2461  136989  144919  122136  156492   82231  177680  114904    1065
    3780    1094    3183     512     270     510     871    2851     749
    2397     730    3015    2102     453   18212     261     408    2533
    1102     335    1015    1952    3518    1856  600974   14859    7307
   19936    7267   26754   25531   10051    9066   10567   18585   33672
   16591    9312   10674    4837   18051    9976   10057    7674   12435
   18023   14953   30777   22964   10174  144651   24247   13707   17482
   19864   23020    7618    4368    9058   15025   17093   19632   20532
   64495   26880   42611   20182   19726   20845    8263   64448   10809
   26690   95028   19506   11864   56766   26867   22503   13036   54228
   26798   31000   23753    4005     666   61597  154852   55557    8041
   28805   33426   23407 1414431    5910    3516    1218  174392  234889
   10708    9581    5108   13469   11308   21143    2176    3357    9917
     848    4093   20549    8499   34494   20226   10391   12474    8122
   24242    6415    5940    7181     159   11700   11495    3467   57243
    9159  141885    7985    4417   77335    6308   14120   13492   16741
   48872    3465    9496    2935   30983   26786   15244   22472   13804
   29639   21757    4939   99157   17394  180454   52857   18514   20675
   10898   39484   21789   21534    4890   10872   30379   30510   20106
   25350   28771   46884   24215   19170    5977   10721   16196    4589
   50907    6801    8834    5753    9857   19404    5534    7724   12736
    7814    6621    2539   12184   13714   84495    4792    7137    7101
   12918   16378    9693   24196   23548    7704   10313   52145    9175
    4773   11367   14268   15309    6371   11031    5971    6575    7032
    5549   74242   11275   34843   95961   78879   61073 1229059   23936
   32469   43501   50662   36412  113515   50359   59639   25747  110294
   21301   61087   36616   46266   34660   73029  176447      33   39641
   23869   68239  119420   76181   55339   35764   27337  313515  583842
  140292  269475  134824  383923  315759  519030  562111  364351  184979
  448304  515481  121295    3556   17131   10270  330122   57318   94618
  150615  100803   58945   84710   87387   45501   29735   39941   17949
  137178   59382  200699   89608  733318  484334   87721   39054  401418
   65577      31  134309   51078 1131401  190759   76292  203673  243482
   50987  204364  597141   55956   41020   74159    1844    2395   39754
    1674    9584    1203    1852    2525    8943    6642    5330  121102
    3235    3453    9140    3613    9017    8267   12590    2960  122121
    2529    7506    6612    7841    6874    7672   12388    4588    5085
   52427    4954   10570  151410   49896    7619    9242    3946   13716
    5159    8552    8135   11115    7828    3654    7250    9030    8490
   17438   16270   16154   11829    6739    9958    6273    3919   12261
    9132    8706    6742   18720    6224    1632   11677   71337    4745
     857     688    7561    6553    9053    4448    5304     420    3646
   13471     246    9095     286    2186    1124     897     568    1077
     361     593   43506   23257   40389   30762   26260   12488   93404
    6460   19598    9555   33342   27510   43461   23673   24082   11453
   24545   20798  171938   19044   11613   40416   23461   23261   22803
   44903   19981   31315   31587   13115   61167   45757    5696   40668
   13602    8538   19729   13832   21576   29828   61864   17294   85484
   15226    8440   18373   47561   12517   67726   14884   11080   18257
    7659   16150    5744   97171    6661   37352   59387      85    9901
   11934   15377   19341   29625   39792    7919   19670   16613   13289
   10962   18276      61   19203   15942       2  185816   13573    9995
   13425   14653  111308    7086   56603   17560     150   27037    7080
   16875   10557   30283   13653    9406   55652   31063  663498    2107
   16548  168327  544701  243070   62997   27957   32348  102836   31056
   73386   61112   23523   43036   73853   22878   20561   51253   33164
   11790   29627     428   20158   42557   97619   19854   26834   73874
   43018  117138   40760   55757   76038   48812   28600   93683   54122
   48564   45382   45687    7000    8043    4500    7199   10104    8530
   31817   25308   21172    4885    9828   16412    9887   16629   17675
    8991   11371   21376    7354   10832   19624   43650   11385    7557
   14668   14843   19972   15852    7031   20003    9868   13640   10153
    6674    8585   62876   55207   21359   12016   58588    5130   12421
   13406    2877   11482   22349   35892    9115    6087   81024    4197
    4353   15389   24117   12613  236165   12300    4182    9846   19893
    8252   68567   10972   38752   30737   10838   15875   77609   16761
   11676   32309    9331    8061   19916   12931    9273   12211   16556
   14777   14757   84528   11378    5678   11972    7358  108137   49096
   38140   16668    9962    8535   14827   36315   12129   15441   35839
   40727   29060   17573   56326   84650   96567   41256   12063    6950
  315146   33121   33605   72054  323097      63   57184   52820   41588
   62549   19283   98950   19559]

deceased_total
[    0   129  1093  1947  1290  1237  1430   853  1124  1053   786  1127
   672  1117   644     3    22    17     1    26     2    11     8    15
    98    20     5     6    14  5997   116    74    75   112   457   309
   159   182   370   430   280    94   106   109   147    88    66   102
   111   339   158   621   468   178  2334   180   271   134   155   255
    36   127   170   192   358   820   396   471   118   236   188    55
  1210    25   545  1798   194   146   838   212   267    99   580   177

In [63]:
# as above last_updated_meta has only one unique value , so droping that column

In [64]:
district.drop('last_updated_meta',axis = 1,inplace = True)

In [65]:
# as above date_meta has only one unique value , so droping that column
district.drop('date_meta',axis = 1,inplace = True)

In [66]:
# droping notes_meta column because of it has only some notes regarding covid data .
district.drop('notes_meta',axis = 1,inplace = True)

In [67]:
# after finding unique values we can see that some noice are present in district_code columns
# so droping that rows

In [68]:
## Rows to remove:

# 7 Foreign Evacuees
# 20 Capital Complex
# 483 State Pool
# 514 BSF Camp
# 527 Evacuees
# 530 Italians
# 588 Airport Quarantine
# 609 Railway Quarantine
# 621 TT
# 3 Unknown
# 11 Other State

In [69]:
district[district['district_code']=='Foreign Evacuees']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
7,AP,Foreign Evacuees,434,434,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [70]:
#droping row of having district_code value 'Foreign Evacuees'
district.drop(7,axis=0,inplace=True)

In [71]:
district[district['district_code']=='Foreign Evacuees']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [72]:
district[district['district_code']=='Capital Complex']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
20,AR,Capital Complex,0,0,0,115210,0,0,0,0,0,0,0,0,0,0,0,0,0,2020-12-24

In [73]:
#droping row of having district_code value 'Foreign Evacuees'
district.drop(20,axis=0,inplace=True)

In [74]:
district[district['district_code']=='Capital Complex']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [75]:
district[district['district_code']=='State Pool']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
483,OR,State Pool,32048,31587,0,0,0,0,53,57,0,0,0,338,401,0,0,0,0,0

In [76]:
#droping row of having district_code value 'Foreign Evacuees'
district.drop(483,axis=0,inplace=True)

In [77]:
district[district['district_code']=='State Pool']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [78]:
district[district['district_code']=='BSF Camp']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
514,RJ,BSF Camp,85,85,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [79]:
#droping row of having district_code value 'BSF Camp'
district.drop(514,axis=0,inplace=True)

In [80]:
district[district['district_code']=='BSF Camp']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [81]:
district[district['district_code']=='Evacuees']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
527,RJ,Evacuees,61,61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [82]:
#droping row of having district_code value 'Evacuees'
district.drop(527,axis=0,inplace=True)

In [83]:
district[district['district_code']=='Evacuees']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [84]:
district[district['district_code']=='Italians']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
530,RJ,Italians,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [85]:
#droping row of having district_code value 'Italians'
district.drop(530,axis=0,inplace=True)

In [86]:
district[district['district_code']=='Italians']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [87]:
district[district['district_code']=='Airport Quarantine']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
588,TN,Airport Quarantine,2113,2107,2,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0

In [88]:
#droping row of having district_code value 'Airport Quarantine'
district.drop(588,axis=0,inplace=True)

In [89]:
district[district['district_code']=='Airport Quarantine']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [90]:
district[district['district_code']=='Railway Quarantine']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
609,TN,Railway Quarantine,428,428,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [91]:
#droping row of having district_code value 'Railway Quarantine'
district.drop(609,axis=0,inplace=True)

In [92]:
district[district['district_code']=='Railway Quarantine']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [93]:
district[district['state_code']=='TT']

Empty DataFrame
Columns: [state_code, district_code, confirmed_total, recovered_total, deceased_total, tested_total, vaccinated1_total, vaccinated2_total, confirmed_delta, recovered_delta, deceased_delta, vaccinated1_delta, vaccinated2_delta, confirmed_delta7, recovered_delta7, deceased_delta7, vaccinated1_delta7, vaccinated2_delta7, population_meta, tested_meta]
Index: []

In [94]:
# ,In order to get the testing ratio , we first checked and removed those districts which had both population and tested data missing,
# there is a district name that is 'Unknown' both population and tested data missing.
#  we first checked and removed those districts which had both population and tested data missing.

In [95]:
district[district['district_code']=='Unknown']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
3,AN,Unknown,7651,7518,129,0,0,0,0,0,0,0,0,3,5,0,0,0,0,0
77,AS,Unknown,610645,600974,5997,0,0,0,212,236,1,0,0,2056,2215,24,0,0,0,0
153,GA,Unknown,178108,174392,3364,0,0,0,23,53,0,0,0,222,409,6,0,0,0,0
245,JH,Unknown,0,0,0,0,0,0,0,0,0,0,0,-166,-70,0,0,0,0,0
378,MN,Unknown,123731,121102,1921,0,0,0,63,62,1,0,0,439,652,10,0,0,0,0
431,MP,Unknown,1416,1632,1493,0,0,0,0,8,0,0,0,0,74,1,0,0,0,0
552,SK,Unknown,31979,31063,396,0,0,0,21,8,1,0,0,79,76,2,0,0,0,0
582,TG,Unknown,671463,663498,3956,0,0,0,121,183,1,0,0,1189,1121,9,0,0,0,0

In [96]:
district.drop([3,77,153,245,378,431,552,582],axis=0,inplace=True)

In [97]:
district.shape

(732, 20)

In [98]:
district[district['district_code']=='Other State']

,state_code,district_code,confirmed_total,recovered_total,deceased_total,tested_total,vaccinated1_total,vaccinated2_total,confirmed_delta,recovered_delta,deceased_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta7,recovered_delta7,deceased_delta7,vaccinated1_delta7,vaccinated2_delta7,population_meta,tested_meta
11,AP,Other State,2461,2461,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
139,CT,Other State,805,666,131,0,0,0,1,0,0,0,0,4,3,0,0,0,0,0
177,GJ,Other State,162,159,3,108,0,0,0,0,0,0,0,0,0,0,0,0,0,2020-06-27
289,KA,Other State,36,33,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
337,MH,Other State,144,31,111,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
540,RJ,Other State,189,150,39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
740,WB,Other State,66,63,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [99]:
# as above there are some rows that district name is 'OTHER STATE', replacing and renaming that district name as 'Other District'.

In [100]:
district['district_code'] = district['district_code'].str.replace('Other State','Other District')

In [101]:
# district.drop([11,139,289,337,540,740],axis=0,inplace=True)

In [102]:
district.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 732 entries, 0 to 747
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state_code          732 non-null    object
 1   district_code       732 non-null    object
 2   confirmed_total     732 non-null    int64
 3   recovered_total     732 non-null    int64
 4   deceased_total      732 non-null    int64
 5   tested_total        732 non-null    int64
 6   vaccinated1_total   732 non-null    int64
 7   vaccinated2_total   732 non-null    int64
 8   confirmed_delta     732 non-null    int64
 9   recovered_delta     732 non-null    int64
 10  deceased_delta      732 non-null    int64
 11  vaccinated1_delta   732 non-null    int64
 12  vaccinated2_delta   732 non-null    int64
 13  confirmed_delta7    732 non-null    int64
 14  recovered_delta7    732 non-null    int64
 15  deceased_delta7     732 non-null    int64
 16  vaccinated1_delta7  732 non-null    int64
 17  vaccinated2_delta7  732 non-null    int64
 18  population_meta     732 non-null    int64
 19  tested_meta         732 non-null    object
dtypes: int64(17), object(3)
memory usage: 120.1+ KB

In [103]:
district.columns

Index(['state_code', 'district_code', 'confirmed_total', 'recovered_total',
       'deceased_total', 'tested_total', 'vaccinated1_total',
       'vaccinated2_total', 'confirmed_delta', 'recovered_delta',
       'deceased_delta', 'vaccinated1_delta', 'vaccinated2_delta',
       'confirmed_delta7', 'recovered_delta7', 'deceased_delta7',
       'vaccinated1_delta7', 'vaccinated2_delta7', 'population_meta',
       'tested_meta'],
      dtype='object')

In [104]:
district['state_code'].nunique()

36

In [105]:
district['state_code'].unique()

array(['AN', 'AP', 'AR', 'AS', 'BR', 'CH', 'CT', 'DL', 'DN', 'GA', 'GJ',
       'HP', 'HR', 'JH', 'JK', 'KA', 'KL', 'LA', 'LD', 'MH', 'ML', 'MN',
       'MP', 'MZ', 'NL', 'OR', 'PB', 'PY', 'RJ', 'SK', 'TG', 'TN', 'TR',
       'UP', 'UT', 'WB'], dtype=object)