In [15]:
import pandas as pd
import requests
import json

In [16]:
#creating data frame of timeseries dataset.

In [17]:
# Replace with the JSON URL
timeseries_url = "https://data.covid19india.org/v4/min/timeseries.min.json"

In [18]:
# Fetch the JSON data
timeseries_data = requests.get(timeseries_url)
timeseries = timeseries_data.json()

In [19]:

# Create lists to store the data
data = []
for state_code, state_data in timeseries.items():
    dates_data = state_data.get('dates', {})
    for date, date_data in dates_data.items():
        total_data = date_data.get('total', {})
        delta_data = date_data.get('delta', {})
        delta7_data = date_data.get('delta7', {})
        row = {
            "StateCode": state_code,
            "Date": date,
            "Confirmed": total_data.get('confirmed', 0),
            "Deceased": total_data.get('deceased', 0),
            "Recovered": total_data.get('recovered', 0),
            "Tested": total_data.get('tested', 0),
            "Vaccinated1": total_data.get('vaccinated1', 0),
            "Vaccinated2": total_data.get('vaccinated2', 0),
            "DeltaConfirmed": delta_data.get('confirmed', 0),
            "DeltaDeceased": delta_data.get('deceased', 0),
            "DeltaRecovered": delta_data.get('recovered', 0),
            "DeltaTested": delta_data.get('tested', 0),
            "DeltaVaccinated1": delta_data.get('vaccinated1', 0),
            "DeltaVaccinated2": delta_data.get('vaccinated2', 0),
            "Delta7Confirmed": delta7_data.get('confirmed', 0),
            "Delta7Deceased": delta7_data.get('deceased', 0),
            "Delta7Recovered": delta7_data.get('recovered', 0),
            "Delta7Tested": delta7_data.get('tested', 0),
            "Delta7Vaccinated1": delta7_data.get('vaccinated1', 0),
            "Delta7Vaccinated2": delta7_data.get('vaccinated2', 0),
        }
        data.append(row)

# Create a DataFrame
timeseries = pd.DataFrame(data)

# Save the DataFrame as a CSV file
timeseries.to_csv("covid_timeseries_data.csv", index=False)

In [20]:
timeseries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21678 entries, 0 to 21677
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StateCode          21678 non-null  object
 1   Date               21678 non-null  object
 2   Confirmed          21678 non-null  int64
 3   Deceased           21678 non-null  int64
 4   Recovered          21678 non-null  int64
 5   Tested             21678 non-null  int64
 6   Vaccinated1        21678 non-null  int64
 7   Vaccinated2        21678 non-null  int64
 8   DeltaConfirmed     21678 non-null  int64
 9   DeltaDeceased      21678 non-null  int64
 10  DeltaRecovered     21678 non-null  int64
 11  DeltaTested        21678 non-null  int64
 12  DeltaVaccinated1   21678 non-null  int64
 13  DeltaVaccinated2   21678 non-null  int64
 14  Delta7Confirmed    21678 non-null  int64
 15  Delta7Deceased     21678 non-null  int64
 16  Delta7Recovered    21678 non-null  int64
 17  Delta7Tested       21678 non-null  int64
 18  Delta7Vaccinated1  21678 non-null  int64
 19  Delta7Vaccinated2  21678 non-null  int64
dtypes: int64(18), object(2)
memory usage: 3.3+ MB

In [21]:
# checking null values
timeseries.isnull().sum()

StateCode            0
Date                 0
Confirmed            0
Deceased             0
Recovered            0
Tested               0
Vaccinated1          0
Vaccinated2          0
DeltaConfirmed       0
DeltaDeceased        0
DeltaRecovered       0
DeltaTested          0
DeltaVaccinated1     0
DeltaVaccinated2     0
Delta7Confirmed      0
Delta7Deceased       0
Delta7Recovered      0
Delta7Tested         0
Delta7Vaccinated1    0
Delta7Vaccinated2    0
dtype: int64

In [22]:
# checking duplicate values
timeseries.duplicated().sum()

0

In [23]:
timeseries.shape

(21678, 20)

In [24]:
# for checking unique values
for i in timeseries:
  print(i)
  print(timeseries[i].unique())
  print()

StateCode
['AN' 'AP' 'AR' 'AS' 'BR' 'CH' 'CT' 'DL' 'DN' 'GA' 'GJ' 'HP' 'HR' 'JH'
 'JK' 'KA' 'KL' 'LA' 'LD' 'MH' 'ML' 'MN' 'MP' 'MZ' 'NL' 'OR' 'PB' 'PY'
 'RJ' 'SK' 'TG' 'TN' 'TR' 'TT' 'UN' 'UP' 'UT' 'WB']

Date
['2020-03-26' '2020-03-27' '2020-03-28' '2020-03-29' '2020-03-30'
 '2020-03-31' '2020-04-01' '2020-04-02' '2020-04-03' '2020-04-04'
 '2020-04-05' '2020-04-06' '2020-04-07' '2020-04-08' '2020-04-09'
 '2020-04-10' '2020-04-11' '2020-04-12' '2020-04-13' '2020-04-14'
 '2020-04-15' '2020-04-16' '2020-04-17' '2020-04-18' '2020-04-19'
 '2020-04-20' '2020-04-21' '2020-04-22' '2020-04-23' '2020-04-24'
 '2020-04-25' '2020-04-26' '2020-04-27' '2020-04-28' '2020-04-29'
 '2020-04-30' '2020-05-01' '2020-05-02' '2020-05-03' '2020-05-04'
 '2020-05-05' '2020-05-06' '2020-05-07' '2020-05-08' '2020-05-09'
 '2020-05-10' '2020-05-11' '2020-05-12' '2020-05-13' '2020-05-14'
 '2020-05-15' '2020-05-16' '2020-05-17' '2020-05-18' '2020-05-19'
 '2020-05-20' '2020-05-21' '2020-05-22' '2020-05-23' '2020-05-24'
 '2020-05-25' '2020-05-26' '2020-05-27' '2020-05-28' '2020-05-29'
 '2020-05-30' '2020-05-31' '2020-06-01' '2020-06-02' '2020-06-03'
 '2020-06-04' '2020-06-05' '2020-06-06' '2020-06-07' '2020-06-08'
 '2020-06-09' '2020-06-10' '2020-06-11' '2020-06-12' '2020-06-13'
 '2020-06-14' '2020-06-15' '2020-06-16' '2020-06-17' '2020-06-18'
 '2020-06-19' '2020-06-20' '2020-06-21' '2020-06-22' '2020-06-23'
 '2020-06-24' '2020-06-25' '2020-06-26' '2020-06-27' '2020-06-28'
 '2020-06-29' '2020-06-30' '2020-07-01' '2020-07-02' '2020-07-03'
 '2020-07-04' '2020-07-05' '2020-07-06' '2020-07-07' '2020-07-08'
 '2020-07-09' '2020-07-10' '2020-07-11' '2020-07-12' '2020-07-13'
 '2020-07-14' '2020-07-15' '2020-07-16' '2020-07-17' '2020-07-18'
 '2020-07-19' '2020-07-20' '2020-07-21' '2020-07-22' '2020-07-23'
 '2020-07-24' '2020-07-25' '2020-07-26' '2020-07-27' '2020-07-28'
 '2020-07-29' '2020-07-30' '2020-07-31' '2020-08-01' '2020-08-02'
 '2020-08-03' '2020-08-04' '2020-08-05' '2020-08-06' '2020-08-07'
 '2020-08-08' '2020-08-09' '2020-08-10' '2020-08-11' '2020-08-12'
 '2020-08-13' '2020-08-14' '2020-08-15' '2020-08-16' '2020-08-17'
 '2020-08-18' '2020-08-19' '2020-08-20' '2020-08-21' '2020-08-22'
 '2020-08-23' '2020-08-24' '2020-08-25' '2020-08-26' '2020-08-27'
 '2020-08-28' '2020-08-29' '2020-08-30' '2020-08-31' '2020-09-01'
 '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05' '2020-09-06'
 '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10' '2020-09-11'
 '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15' '2020-09-16'
 '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20' '2020-09-21'
 '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25' '2020-09-26'
 '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30' '2020-10-01'
 '2020-10-02' '2020-10-03' '2020-10-04' '2020-10-05' '2020-10-06'
 '2020-10-07' '2020-10-08' '2020-10-09' '2020-10-10' '2020-10-11'
 '2020-10-12' '2020-10-13' '2020-10-14' '2020-10-15' '2020-10-16'
 '2020-10-17' '2020-10-18' '2020-10-19' '2020-10-20' '2020-10-21'
 '2020-10-22' '2020-10-23' '2020-10-24' '2020-10-25' '2020-10-26'
 '2020-10-27' '2020-10-28' '2020-10-29' '2020-10-30' '2020-10-31'
 '2020-11-01' '2020-11-02' '2020-11-03' '2020-11-04' '2020-11-05'
 '2020-11-06' '2020-11-07' '2020-11-08' '2020-11-09' '2020-11-10'
 '2020-11-11' '2020-11-12' '2020-11-13' '2020-11-14' '2020-11-15'
 '2020-11-16' '2020-11-17' '2020-11-18' '2020-11-19' '2020-11-20'
 '2020-11-21' '2020-11-22' '2020-11-23' '2020-11-24' '2020-11-25'
 '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29' '2020-11-30'
 '2020-12-01' '2020-12-02' '2020-12-03' '2020-12-04' '2020-12-05'
 '2020-12-06' '2020-12-07' '2020-12-08' '2020-12-09' '2020-12-10'
 '2020-12-11' '2020-12-12' '2020-12-13' '2020-12-14' '2020-12-15'
 '2020-12-16' '2020-12-17' '2020-12-18' '2020-12-19' '2020-12-20'
 '2020-12-21' '2020-12-22' '2020-12-23' '2020-12-24' '2020-12-25'
 '2020-12-26' '2020-12-27' '2020-12-28' '2020-12-29' '2020-12-30'
 '2020-12-31' '2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04'
 '2021-01-05' '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09'
 '2021-01-10' '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14'
 '2021-01-15' '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19'
 '2021-01-20' '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24'
 '2021-01-25' '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29'
 '2021-01-30' '2021-01-31' '2021-02-01' '2021-02-02' '2021-02-03'
 '2021-02-04' '2021-02-05' '2021-02-06' '2021-02-07' '2021-02-08'
 '2021-02-09' '2021-02-10' '2021-02-11' '2021-02-12' '2021-02-13'
 '2021-02-14' '2021-02-15' '2021-02-16' '2021-02-17' '2021-02-18'
 '2021-02-19' '2021-02-20' '2021-02-21' '2021-02-22' '2021-02-23'
 '2021-02-24' '2021-02-25' '2021-02-26' '2021-02-27' '2021-02-28'
 '2021-03-01' '2021-03-02' '2021-03-03' '2021-03-04' '2021-03-05'
 '2021-03-06' '2021-03-07' '2021-03-08' '2021-03-09' '2021-03-10'
 '2021-03-11' '2021-03-12' '2021-03-13' '2021-03-14' '2021-03-15'
 '2021-03-16' '2021-03-17' '2021-03-18' '2021-03-19' '2021-03-20'
 '2021-03-21' '2021-03-22' '2021-03-23' '2021-03-24' '2021-03-25'
 '2021-03-26' '2021-03-27' '2021-03-28' '2021-03-29' '2021-03-30'
 '2021-03-31' '2021-04-01' '2021-04-02' '2021-04-03' '2021-04-04'
 '2021-04-05' '2021-04-06' '2021-04-07' '2021-04-08' '2021-04-09'
 '2021-04-10' '2021-04-11' '2021-04-12' '2021-04-13' '2021-04-14'
 '2021-04-15' '2021-04-16' '2021-04-17' '2021-04-18' '2021-04-19'
 '2021-04-20' '2021-04-21' '2021-04-22' '2021-04-23' '2021-04-24'
 '2021-04-25' '2021-04-26' '2021-04-27' '2021-04-28' '2021-04-29'
 '2021-04-30' '2021-05-01' '2021-05-02' '2021-05-03' '2021-05-04'
 '2021-05-05' '2021-05-06' '2021-05-07' '2021-05-08' '2021-05-09'
 '2021-05-10' '2021-05-11' '2021-05-12' '2021-05-13' '2021-05-14'
 '2021-05-15' '2021-05-16' '2021-05-17' '2021-05-18' '2021-05-19'
 '2021-05-20' '2021-05-21' '2021-05-22' '2021-05-23' '2021-05-24'
 '2021-05-25' '2021-05-26' '2021-05-27' '2021-05-28' '2021-05-29'
 '2021-05-30' '2021-05-31' '2021-06-01' '2021-06-02' '2021-06-03'
 '2021-06-04' '2021-06-05' '2021-06-06' '2021-06-07' '2021-06-08'
 '2021-06-09' '2021-06-10' '2021-06-11' '2021-06-12' '2021-06-13'
 '2021-06-14' '2021-06-15' '2021-06-16' '2021-06-17' '2021-06-18'
 '2021-06-19' '2021-06-20' '2021-06-21' '2021-06-22' '2021-06-23'
 '2021-06-24' '2021-06-25' '2021-06-26' '2021-06-27' '2021-06-28'
 '2021-06-29' '2021-06-30' '2021-07-01' '2021-07-02' '2021-07-03'
 '2021-07-04' '2021-07-05' '2021-07-06' '2021-07-07' '2021-07-08'
 '2021-07-09' '2021-07-10' '2021-07-11' '2021-07-12' '2021-07-13'
 '2021-07-14' '2021-07-15' '2021-07-16' '2021-07-17' '2021-07-18'
 '2021-07-19' '2021-07-20' '2021-07-21' '2021-07-22' '2021-07-23'
 '2021-07-24' '2021-07-25' '2021-07-26' '2021-07-27' '2021-07-28'
 '2021-07-29' '2021-07-30' '2021-07-31' '2021-08-01' '2021-08-02'
 '2021-08-03' '2021-08-04' '2021-08-05' '2021-08-06' '2021-08-07'
 '2021-08-08' '2021-08-09' '2021-08-10' '2021-08-11' '2021-08-12'
 '2021-08-13' '2021-08-14' '2021-08-15' '2021-08-16' '2021-08-17'
 '2021-08-18' '2021-08-19' '2021-08-20' '2021-08-21' '2021-08-22'
 '2021-08-23' '2021-08-24' '2021-08-25' '2021-08-26' '2021-08-27'
 '2021-08-28' '2021-08-29' '2021-08-30' '2021-08-31' '2021-09-01'
 '2021-09-02' '2021-09-03' '2021-09-04' '2021-09-05' '2021-09-06'
 '2021-09-07' '2021-09-08' '2021-09-09' '2021-09-10' '2021-09-11'
 '2021-09-12' '2021-09-13' '2021-09-14' '2021-09-15' '2021-09-16'
 '2021-09-17' '2021-09-18' '2021-09-19' '2021-09-20' '2021-09-21'
 '2021-09-22' '2021-09-23' '2021-09-24' '2021-09-25' '2021-09-26'
 '2021-09-27' '2021-09-28' '2021-09-29' '2021-09-30' '2021-10-01'
 '2021-10-02' '2021-10-03' '2021-10-04' '2021-10-05' '2021-10-06'
 '2021-10-07' '2021-10-08' '2021-10-09' '2021-10-10' '2021-10-11'
 '2021-10-12' '2021-10-13' '2021-10-14' '2021-10-15' '2021-10-16'
 '2021-10-17' '2021-10-18' '2021-10-19' '2021-10-20' '2021-10-21'
 '2021-10-22' '2021-10-23' '2021-10-24' '2021-10-25' '2021-10-26'
 '2021-10-27' '2021-10-28' '2021-10-29' '2021-10-30' '2021-10-31'
 '2020-03-12' '2020-03-13' '2020-03-14' '2020-03-15' '2020-03-16'
 '2020-03-17' '2020-03-18' '2020-03-19' '2020-03-20' '2020-03-21'
 '2020-03-22' '2020-03-23' '2020-03-24' '2020-03-25' '2020-03-02'
 '2020-03-03' '2020-03-04' '2020-03-05' '2020-03-06' '2020-03-07'
 '2020-03-08' '2020-03-09' '2020-03-10' '2020-03-11' '2020-01-30'
 '2020-02-02' '2020-02-03' '2020-02-14']

Confirmed
[      1       6       9 ... 1591014 1591994 1592908]

Deceased
[    0     1     2 ... 19113 19126 19141]

Recovered
[      0      10      11 ... 1563678 1564558 1565471]

Tested
[       0     1403     2679 ... 19133755 19180886 19228303]

Vaccinated1
[       0      225      442 ... 55226050 55982557 56192166]

Vaccinated2
[       0      182      495 ... 21196433 21500866 21559747]

DeltaConfirmed
[  1   5   3 ... 557 744 914]

DeltaDeceased
[   0    1    2    3    4    5    8   10    7   11   12    6   14   13
   15   17   19   37   43   44   40   42   52   56   54   62   65   61
   49   58   68   67   63   77   72   89   97   80   87   93   82   88
   86   95   91   92   81   85   84   75   76   71   70   73   74   66
   60   69   64   57   51   45   48   35   41   31   38   33   34   30
   32   28   25   24   23   27   16   20   22   21   18    9   83   96
  108   98  101  109   99  106  114  104  118  103   94   90   59   53
   50   36   29   26   55   46   47   79  105  111  107 3971   39  123
  122  132  156  120  135  138  158  170  175  191  193  207  219  218
  199  226  246  279  251  269  229  266  210  253  212  208  223  189
  172  153  195  129  144  149  146  113   -1  437  131  121  112  141
  167  161  240  277  249  306  348  357  350  380  381  368  395  375
  412  407  448  338  311  335  341  332  273  319  347  300  308  289
  337  262  340  265  235  233  252  182  130  117  139   78  110  125
  137  142  152  157  174  180  173  140  133  119  102  145  181  177
  162  155  151  165  163  164  124  128  169  115  136  100  116  126
  127  148  179  190  143  201  270  217  271  239  288  346  328  592
  482  490  596  480  516  344  373  349  403  476  525  468  548  353
  451  624  529  588  530  401  492  411  464  463  514  364  365  320
  192  194  159  168  176  188  196  198  186  213  209  227  211  171
  206  166  147  150  187  160  197  215  178  214  134  563  363  281
  622  708  471  358 1409  248  245  295  204  224  258  280  298  278
  257  267  282  322  260  334  316  275  390  293  256  413  228  422
  326  339  297  329  355  331  296  184  292  391  378  312  423  495
  442  416  515  474  440  425  455  392  479  459  430  481  394  424
  263  370  302  305  154  222  376  301  309  398  419  503  351  519
  568  773  676  832  524  895 1035  771  828  802  669  567  891  920
  853  898  864  572  549  793  816  850  695  960  974 1000 1291  594
  984 1263  682 1320 1137  992  884  973  814  500  854  553  643 1377
  741  618  702  661 1915 2619 1966 2771 1592 1458 1236  636  648  605
  352  508  556  511  405  287  231  371  439  738  494 3656  254  286
  225  216  183 1481 -145  -10  202  185  518  241  236  232  303  397
  467  404  475  486  493  478  483  460  443  434  409  374  268  205
  259  274  261  272  388  324  396 2004  343  426  414  384  417  506
  438  444  611  421  473  520  541  497  582  614  680  543  675  671
 1130  755  763  703  704  642  774  775  784  765  760  806  849  919
  899  936  875 1013  887  835  950 1006  989  952  880 1099  979  981
  953  918  846 1066 1017 1019  943 1027 1026 1083 1044 1005 1129 1107
 1168 1213 1202 1111 1140 1054 1281 1175 1221 1149 1135 1056 1085 1123
 1144 1093 1124 1040 1178 1179 1068  937  903  886  990  963  967  929
  921  813  710  727  690  882  840 1032  589  714  701  686  655  578
  491  562  550  469  498  510  707  672  577  557  450  544  517  472
  586  564  499  489  501  526  386  402  354  356  342  315  250  285
  299  244  237  200  458  713  477  446  630  684  838  904 1038 1184
 1338 1498 1620 1757 2021 2101 2257 2620 2761 2808 2762 3286 3646 3502
 3525 3685 3423 3439 3786 3979 3923 4233 4092 3749 3879 4198 4128 4000
 3889 4077 4098 4334 4529 3877 4209 4194 3739 4454 3509 4160 3843 3659
 3611 3463 3130 2783 3205 2898 2717 3372 2682 2444 2107 2222 6139 3414
 3996 3300 3922 2733 2540 2329 1591 1645 1574 1424 1167 1359 1323 1328
 1183 1258  978  907  819 1002  857  737  725  552  930  908 1207  720
 2024  625  560  372 3998  542  418  641  640  598  420  561  532  465
  616  447  496  583  527  385  650  457  462  507  290  310  432  318
  291  276  313  242  247  666  559  584  734  805  551  445  264  304
  294  255   -3  221]

DeltaRecovered
[  0  10   1 ... 628 683 795]

DeltaTested
[    0  1403  1276 ... 45437 49017 47417]

DeltaVaccinated1
[     0    225    217 ... 701727 756507 209609]

DeltaVaccinated2
[     0    182    313 ... 317576 304433  58881]

Delta7Confirmed
[   1    6    9 ... 6386 6522 6528]

Delta7Deceased
[  0   1   2 ... 612 589 540]

Delta7Recovered
[   0   10    1 ... 5796 5868 5953]

Delta7Tested
[     0   1403   1276 ... 291347 295319 300114]

Delta7Vaccinated1
[      0     225     442 ... 3980686 3809335 3809597]

Delta7Vaccinated2
[      0     182     495 ... 1879824 1870225 1871612]

In [25]:
timeseries['StateCode'].nunique()

38

In [26]:
# as per above unique values , we have 28 state + 8 union terroriry so nunique of timeseries['StateCode'] should be 36 , but we are getting total 38 .
 # so removing data of states which are not in Inida- that is TT and UN

In [27]:
timeseries[timeseries['StateCode']=='TT']

,StateCode,Date,Confirmed,Deceased,Recovered,Tested,Vaccinated1,Vaccinated2,DeltaConfirmed,DeltaDeceased,DeltaRecovered,DeltaTested,DeltaVaccinated1,DeltaVaccinated2,Delta7Confirmed,Delta7Deceased,Delta7Recovered,Delta7Tested,Delta7Vaccinated1,Delta7Vaccinated2
19206,TT,2020-01-30,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0
19207,TT,2020-02-02,2,0,0,0,0,0,1,0,0,0,0,0,2,0,0,0,0,0
19208,TT,2020-02-03,3,0,0,0,0,0,1,0,0,0,0,0,3,0,0,0,0,0
19209,TT,2020-02-14,3,0,3,0,0,0,0,0,3,0,0,0,0,0,3,0,0,0
19210,TT,2020-03-02,5,0,3,0,0,0,2,0,0,0,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19814,TT,2021-10-27,34231243,456418,33606777,604498405,723497151,317002722,16351,734,17077,1290900,1939426,3234870,104536,3574,118586,8756187,17828127,24133671
19815,TT,2021-10-28,34245550,457223,33619966,605885769,726445742,321755224,14307,805,13189,1387364,2948591,4752502,103069,4147,113133,8819288,17058938,25237448
19816,TT,2021-10-29,34259765,457774,33633515,607062619,728940103,325373874,14215,551,13549,1176850,2494361,3618650,100957,4032,109046,8631457,16526747,24758819
19817,TT,2021-10-30,34272705,458219,33648187,608319915,731621098,329819237,12940,445,14672,1257296,2680995,4445363,97818,3918,107209,8548595,15887789,24509288
19818,TT,2021-10-31,34285612,458470,33661339,609201294,732371508,330752697,12907,251,13152,881379,750410,933460,96071,3727,101753,8431577,15883780,24527530

In [28]:
timeseries[timeseries['StateCode']=='UN']

,StateCode,Date,Confirmed,Deceased,Recovered,Tested,Vaccinated1,Vaccinated2,DeltaConfirmed,DeltaDeceased,DeltaRecovered,DeltaTested,DeltaVaccinated1,DeltaVaccinated2,Delta7Confirmed,Delta7Deceased,Delta7Recovered,Delta7Tested,Delta7Vaccinated1,Delta7Vaccinated2
19819,UN,2020-05-19,814,0,0,0,0,0,814,0,0,0,0,0,814,0,0,0,0,0
19820,UN,2020-05-20,1096,0,0,0,0,0,282,0,0,0,0,0,1096,0,0,0,0,0
19821,UN,2020-05-21,1403,0,0,0,0,0,307,0,0,0,0,0,1403,0,0,0,0,0
19822,UN,2020-05-22,1620,0,0,0,0,0,217,0,0,0,0,0,1620,0,0,0,0,0
19823,UN,2020-05-23,1899,0,0,0,0,0,279,0,0,0,0,0,1899,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19876,UN,2020-07-15,1524,0,0,0,0,0,-655,0,0,0,0,0,-3494,0,0,0,0,0
19877,UN,2020-07-16,1285,0,0,0,0,0,-239,0,0,0,0,0,-3100,0,0,0,0,0
19878,UN,2020-07-17,531,0,0,0,0,0,-754,0,0,0,0,0,-3630,0,0,0,0,0
19879,UN,2020-07-18,163,0,0,0,0,0,-368,0,0,0,0,0,-3253,0,0,0,0,0
19880,UN,2020-07-19,0,0,0,0,0,0,-163,0,0,0,0,0,-3024,0,0,0,0,0

In [29]:
# as  you see above , there is multiple row of UN STATE AND TT STATE which are not in india.
#  so Further cleaning has been done in SQL , cleaning notes have been provided for reference .